name: coupons
on:
  push:
    branches: [main]  # 确保分支名正确（非 master）
  schedule:
    - cron: '23 14 * * *'  # UTC 时间 11:58（北京时间 19:58）

jobs:
  run-coupons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # ✅ 使用稳定版本 v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # ✅ 升级到 v3
        with:
          node-version: 14  # 建议升级到 LTS 版本（如 18/20）

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node ./app.js
